fail if triggered by branch

diff --git a/.github/workflows/release-dev-container.yml b/.github/workflows/release-dev-container.yml
--- a/.github/workflows/release-dev-container.yml
+++ b/.github/workflows/release-dev-container.yml
@@ -14,9 +14,16 @@ jobs:
     name: 'Production'
     runs-on: ubuntu-latest
 
-#    if: startsWith(github.ref, 'refs/tags/') && github.ref_name == 'main'
-
     steps:
+
+      - name: Check if triggered by tag
+        id: check_tag
+        run: |
+          if [[ -z "${{ github.ref_name }}" || "${{ github.ref_type }}" != "tag" ]]; then
+            echo "This workflow should only be triggered by a tag. Failing."
+            exit 1
+          fi
+
       # Checkout the repository to the GitHub Actions runner
       - name: Checkout
         uses: actions/checkout@v3
